### ISSUE TITLE
CoFHAPI:energy

### ISSUE THREAD

**Issue by ScottDTA** [K-4U/Hydraulicraft#117]
When I try to use the new version in my mudpack, it wont start.  Says it is missing the CoFHAPI:energy
If I use the previous version it loads just fine.  I think it is a mod loading order issue, but not sure why it happens with the newest version, but not the previous one.

**Comment by K-4U** [comment]
Do you have an rf based mod installed? 
It shouldn't have changed..

**Comment by ScottDTA** [comment]
Yea, I think it is something in the mix of the mods in the pack.  

https://www.dropbox.com/s/8xd0l8ub8lzvv1p/neiintegration_loadedmod.csv?dl=0

**Comment by ScottDTA** [comment]
Some reason with that list of mods it looks like it is Enabling HydCraft before k4lib, which I think is why it is complaining.  Not really sure why It is doing that.

**Comment by ScottDTA** [comment]
Got it to work with the newest versions of CoFH files that were uploaded in the last couple days.  Would not work with the ones I had (about 4 version out of date)

**Comment by K-4U** [comment]
Sooo.. it's solved?

**Comment by ScottDTA** [comment]
It appears so, yes.  Sorry to have taken your time.

**Comment by K-4U** [comment]
No worries! I'd much rather you report something that's not an actual issue then not report anything at all!
