### ISSUE TITLE
Pipes should "reform" after adjacent/intersecting pipe is removed. 

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#123]
![2015-06-05_11 27 34](https://cloud.githubusercontent.com/assets/11265900/8012424/404f9f22-0b76-11e5-81af-73242d63707a.png)

**Comment by K-4U** [comment]
Yeah, i'm still quite surprised how this bug managed to sneak in, as i had fixed it in a previous version. I think i already have a fix, will be done in the next release

**Comment by TheQuadShot** [comment]
While your fixing this :) you should give us a tool (wrench?) that would let me control the pipe connections. like other mods with conduits/pipes.  (I don't like using facades/covers to do it, it doesn't make sense to me)

**Comment by K-4U** [comment]
Hmm.. i was going to add a wrench. Not sure if i'll make it into a yes/no connection. I prefer the method of covers. I'll take it into consideration.
