### ISSUE TITLE
Friction incinerator won't process ores that the crusher can/does

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#125]
I can crush aluminum (from tinkers construct) however the incinerator won't accept it. I haven't tried other ores. I will if you would like.

**Comment by TheQuadShot** [comment]
Ores that don't work(you do crush them):
Any AOBD ore (there are many, only used to make armor/weapons/tools)
Zinc, Blue Power
Platinum, Blue Power, Metallurgy 4
Shiny, Thermal Foundation (becomes platinum after crushing w/aobd ownership)
Osmium, Mekanism
Yellorite, Big Reactors

I'll add more as I find them.

**Comment by TheQuadShot** [comment]
I've upgraded to the latest version of AOBD, which lists hydraulicraft support and no change. hope that helps some.

**Comment by K-4U** [comment]
I haven't done any testing on it, but am still confused. The friction incinerator should just follow the standard smelting registry, so anything that would go in a regular furnace is able to be used with this.

Will do some testing though.

**Comment by K-4U** [comment]
So, after checking with some ores, i haven't been able to find anything. So i'm thinking there's some mod incompatibility. Can you check if the ores you mention do smelt in another furnace?

**Comment by TheQuadShot** [comment]
Ok, I've tested and no, they won't work (smelt). I tried a vanilla furnace and the TCon smeltery. In the mod pack (spaceverse from curse) only has 1 other furnace and it's "broke"(give's error:"Tile Entity Found, Chest. and  Error:  Invalid block) so I can't test on it. I don't have any other way to make ore "chunks". Hope that helps, If I can do more please let me know! Thanks!!

**Comment by K-4U** [comment]
Yeah, i'm thinking that it is an issue with the modpack then.
