### ISSUE TITLE
Low pressure pipes and pump "become" transparent at certain angles

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#131]
![2015-07-15_08 00 28](https://cloud.githubusercontent.com/assets/11265900/8701601/b65cb3ba-2ac7-11e5-9696-5cde058cbfa4.png)
![2015-07-15_07 53 56](https://cloud.githubusercontent.com/assets/11265900/8701513/07b383e8-2ac7-11e5-8483-98e86292fcc1.png)

**Comment by TheQuadShot** [comment]
I'm seeing this on the harvester pistons as well, it may be the ray tracing thing you mentioned.

**Comment by K-4U** [comment]
I've tried to reproduce this, but cannot seem to get it. It may already be fixed. Do you mind trying the latest version from the jenkins?

**Comment by TheQuadShot** [comment]
This works find in Jenkins build .199

**Comment by TheQuadShot** [comment]
oops, ment to close
