### ISSUE TITLE
FluidOil crashes server when generating oil chunk with oil

### ISSUE THREAD

**Issue by EwyBoy** [K-4U/Hydraulicraft#136]
Fluid oil crashes server when generating oil chunk with oil. I don't have the crash report. I just noticed this was a problem when I tried to run a server with the mod installed. Had to remove it to fix the issue.

**Comment by K-4U** [comment]
I'd really prefer it if you could give me a crash log.. That makes finding this bug so much easier..

**Comment by thejams13** [comment]
same thing on my server http://pastebin.com/TwxZdWBd

**Comment by K-4U** [comment]
Could you try updating your forge?
