### ISSUE TITLE
Redstone pressure pumps will always/only align north to south

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#138]
With power side south, and pressure side to the north

**Comment by K-4U** [comment]
Try hitting them on the top with a wrench ;)

**Comment by TheQuadShot** [comment]
oops... didn't think of that, partially cause you don't have a wrench(that I could find) and I couldn't rotate other blocks with one (Archimedes screw, low pressure pump/blocks...).

**Comment by K-4U** [comment]
Wrench is still on my todo list ;)
