### ISSUE TITLE
Lead in a sag mill = nothing/ore lost

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#140]
Copper works fine, but the lead is lost, (not sure who "own's" this though) it does work in an alloy smelter.

**Comment by TheQuadShot** [comment]
filing this over at eio

**Comment by TheQuadShot** [comment]
I'm reopening this because the EIO guy's say that "dustLead" is not registered in the oredict properly.
Sorry, I didn't mean to open a "can of worms"...
https://github.com/SleepyTrousers/EnderIO/issues/2659

**Comment by OndraSter** [comment]
![image](https://cloud.githubusercontent.com/assets/5840290/8765231/b475a73e-2e03-11e5-8fb7-206cc5263c6a.png)

no problem here with latest build (1.7.10-2.3.0.402_beta), crushes to 2 dust + cobble...

**Comment by OndraSter** [comment]
By that I mean, are you using the latest versions? :)

**Comment by K-4U** [comment]
Do you have another one bites the dust in your pack?

**Comment by TheQuadShot** [comment]
No, I don't have aobd, and my test pack is running eio version .381 (release)

**Comment by OndraSter** [comment]
Try latest builds of HC AND latest build of EIO, please :)

**Comment by TheQuadShot** [comment]
Ok same thing, I ran HC .176 and EIO .402_beta and EnderCore .12_alpha
waila and nei are the only other mods I used in this instance

**Comment by K-4U** [comment]
http://ss.k-4u.nl/2015-08-14_15-10-47 Well.. i cannot reproduce it so far.. I'm sorry
