### ISSUE TITLE
scooping a bucket of crude oil gives me a bucket of water

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#143]
I'm running ver. 168

**Comment by TheQuadShot** [comment]
same with hydraulic oil, and lubricant

**Comment by K-4U** [comment]
Cannot reproduce. Might already be fixed. Please try again with the latest dev version!

**Comment by Zsashas** [comment]
Version 2.1.242, this still happens.
![2015-11-16_16 43 56](https://cloud.githubusercontent.com/assets/6917535/11199326/6bc19750-8c81-11e5-8ed7-509cb974f96d.png)
