### ISSUE TITLE
"raw" lonezium image stuck in input slot of washer

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#144]
I processed nadsium after I ran the lonezium and the image is still there, even after I exit from the machine gui. I have to relaunch MC to get it to clear. The opposite is true as well, if I run nadsium first that image will be stuck there as well.

![2015-07-18_16 46 12](https://cloud.githubusercontent.com/assets/11265900/8763992/9e3a0bfe-2d6d-11e5-82f3-f8e859750257.png)

**Comment by OndraSter** [comment]
Known issue, desyncing with the new recipe manager, will fix today :)
