### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by jaxmacky** [K-4U/Hydraulicraft#149]
Game Crash when interacting with a Hydraulic Dynamo with any block in hand, empty hand ok. Installed Buildcraft, as error suggests, and no crash with same interaction. 
Crash Reprt: http://pastebin.com/9VYhs4NY

**Comment by CallMeFoxie** [comment]
Do you still have the crashlog? That pastebin has been removed. Thanks

**Comment by K-4U** [comment]
Closing due to no response from author.
