### ISSUE TITLE
Crash on place two Part Valve together

### ISSUE THREAD

**Issue by bakaxyf** [K-4U/Hydraulicraft#154]
https://gist.github.com/bakaxyf/ba49fc1ff7ce5475d53d

**Comment by K-4U** [comment]
Shit, i was honestly hoping nobody would find this issue. I know of it but am not sure yet how to fix. I honestly thought nobody would ever place the valves together...

**Comment by bakaxyf** [comment]
:p

**Comment by Solidflip** [comment]
I believe were having the same issue?
http://pastebin.com/PQ7HHxgG

**Comment by K-4U** [comment]
Yep you do!
I honestly don't understand why you would place 2 valves next to eachother. But i'll see if i can fix it later. Atm i don't have the time.

**Comment by Solidflip** [comment]
Awesome thanks, It was placed together for testing purposes to see if anything could crash the server, ill make sure it doesnt happen =)

**Comment by K-4U** [comment]
Yeah. Not going to fix this anymore. I've removed the valves from Hydraulicraft because they were causing more problems than they were worth.
