### ISSUE TITLE
How to make a washer? 

### ISSUE THREAD

**Issue by spamenigma** [K-4U/Hydraulicraft#158]
Unsure if mc forum is still used, so posting here too for either help or point out a recipe issue.

To build a 'Washer' we need 'High Pressure Core'
To build a 'High Pressure Core' we need 'Lubricant'
To make 'Lubricant' we need a Filter with 'Refined Nadsium Bicarbinate'
To make 'Refined Nadsium Bicarbinate' we need to put 'Nadsium Bicarbinate' in a 'Washer'
To build a 'Washer'.......... :)

Are we missing some other way of making this or is this an oversight?

Using HydCraft-1.7.10-2.1.227-universal

Thanks

**Comment by K-4U** [comment]
Already reported and fixed in #152, however the fix has not yet been uploaded. I hope to do this soon, as there are some other small fixes to be done.

Also no: i barely look at the MCF post anymore. I should do that more often.

**Comment by spamenigma** [comment]
Great, thanks for responding. Just making sure we weren't going mad! :)
