### ISSUE TITLE
Washer extract issue

### ISSUE THREAD

**Issue by Wykks** [K-4U/Hydraulicraft#161]
I can't pull out stuff inside the washer. It's seems like something is broken about the interface valve.
Insert item / water is working fine thought.
(v 2.1.242 with forge 10.13.4.1492)

Edit : visual http://imgur.com/a/wwmTo (I forgot the insert on enderio conduit in the screenshot, but it doesn't work anyway)
Moar tests : http://imgur.com/jqzuo0e

**Comment by K-4U** [comment]
Will have a look asap. Thanks for reporting
