### ISSUE TITLE
Ore mismatch?

### ISSUE THREAD

**Issue by Solidflip** [K-4U/Hydraulicraft#162]
Im having an issue where with forestry and hydraulicraft installed the Copper ore from hydraulicraft drops apatite ore instead. Not sure if anyone else is having this....

**Comment by K-4U** [comment]
This is weird, Could you check if the copper ore from forestry is properly registered as oreCopper? And under what name is the apatite ore registered? (in the oredict)

**Comment by Solidflip** [comment]
Just checked and Forestry copper is oreCopper and Apatite is oreApatite in the oredict

**Comment by chanzie** [comment]
the lead is dropping thermal expansion copper as well, cannot find the oreDic reference to it..

**Comment by Solidflip** [comment]
Is there any update on this? Or should we wait for the next version for a fix?

**Comment by CallMeFoxie** [comment]
Can you, please, send us your full listings? We are not able to reproduce it.

**Comment by Zsashas** [comment]
Hydraulicraft Lead Ore smelts into Railcraft Steel ingots...

https://gyazo.com/c62fbd2b1855a9a16fba2b30fba72f3d

https://gyazo.com/64f797ceb3622e37b51cf407b3e33a26

**Comment by K-4U** [comment]
@Solidflip @Zsashas @chanzie We would like to get your full mod listings, we're not able to reproduce the issue.

**Comment by K-4U** [comment]
With the rewrite to 1.8.9, this system will be gone.
