### ISSUE TITLE
Various broken stuff

### ISSUE THREAD

**Issue by 1skandar** [K-4U/Hydraulicraft#163]
Something is off about the pressure system. It seems exiting out and coming back in causes the pressure to drop by 200 bars fairly consistently.  It also appears that a redstone pump if drained to 0 RF gets stuck and then will not receive/use RF until you exit and come back in (which is how I found the previous problem). Also, RF usage seems abnormally high. 1,500 RF/t to produce 150 mBar/t of pressure seems quite a bit overkill. 

Also, the Assembler has a nasty bug. Using water it will start making items at 250 bars of pressure. If you are using Hydraulic Oil it won't budge until you have 1250 bars. 

Lastly, it looks like the "waterPressureKills" setting in the config does pretty much nothing. 

Overall, it seems like switching to Hydraulic Oil is currently worthless. Yes, water leaks and doesn't hold as much pressure, but generating enough pressure to take advantage of Hydraulic Oil's higher pressure threshold seems to take forever and the gains really don't seem to be worth it.

**Comment by K-4U** [comment]
Fixed both RF and waterPressureKills

**Comment by 1skandar** [comment]
Please, please look into why the pressure network loses pressure on chunk load/unload. It is extremely difficult to keep the pressure up, not to mention resource intensive.

**Comment by 1skandar** [comment]
Also look into speeding up the Harvester a little. Currently if I add any way to speed up the growth of crops it falls behind. 

Also, if you break the trolleys they often no longer stack in your inventory.

And the pressure drop is still there.

**Comment by 1skandar** [comment]
All looks correct. Closing, and my thanks.
