### ISSUE TITLE
Water pressure still kills even with the config set to false

### ISSUE THREAD

**Issue by Zsashas** [K-4U/Hydraulicraft#165]

**Comment by K-4U** [comment]
Which version are you running?

**Comment by Zsashas** [comment]
HydCraft-1.7.10-2.1.242-universal

I believe this is the latest version.

**Comment by K-4U** [comment]
Looks like i did fix this, but never released the fixed version. I'll do a fixing spree and hopefully release a version with several fixes tomorrow(30-12-2015)
