### ISSUE TITLE
Oil issues with Buildcraft present

### ISSUE THREAD

**Issue by walkerjonny** [K-4U/Hydraulicraft#166]
When I right click with an empty bucket on an oil source from Hydraulicraft I'm getting a water bucket instead of an oil bucket from Hydraulicraft.
By the way, can I use Buildcraft oil with Hydraulicraft instead of Hydraulicraft oil?

**Comment by K-4U** [comment]
Yes, Buildcraft oil and Hydraulicraft oil are interchangeable.
I have no idea as of yet what is causing the water bucket to appear. What version are you running?

**Comment by walkerjonny** [comment]
It was HydCraft-1.7.10-2.1.242-universal.jar at that time but it happens also with newer and older versions.
I'll do some tests to near it down.

**Comment by walkerjonny** [comment]
Now I'm very confused...
I did some tests with just a few mods:
HydCraft-1.7.10-2.1.245-universal.jar
k4lib-1.7.10-0.1.57-universal.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
CoFHCore-[1.7.10]3.0.3-303.jar
CoFHLib-[1.7.10]1.0.3-175.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
MrTJPCore-1.7.10-1.1.0.31-universal.jar
I have still that issue that I'm getting water buckets from the oil sources (now only Hydraulicraft).

**Comment by walkerjonny** [comment]
I had deactivated ore generation and have activated it for testing purposes but with the same result.
