### ISSUE TITLE
Compatibility with Agricraft crops

### ISSUE THREAD

**Issue by blockbreaker1361** [K-4U/Hydraulicraft#167]
It would be nice if your harvester had compat with Agricraft crops as they need to be right clicked for harvesting. I don't know if it's possible, but maybe?

**Comment by K-4U** [comment]
I'll have a word with the Agricraft dev. Maybe he can add support from his side! 
Otherwise i'll have a look at his code, to see how easy it is.

**Comment by K-4U** [comment]
Right, so, kinda late with an update on this but. YAY:
https://github.com/InfinityRaider/AgriCraft/tree/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/compatibility/hydraulicraft
