### ISSUE TITLE
Crash on Server startup - java.lang.NoSuchFieldError: iconRefByID (1.8.9)

### ISSUE THREAD

**Issue by rckymtnrfc** [K-4U/Hydraulicraft#170]
I'm getting a crash when starting the server using HydCraft-1.8.8-3.1.dev-universal.jar and k4lib-1.8.8-1.0.5-universal.jar.  If I remove HydCraft (but leave k4lib), the server starts as expected.

http://pastebin.com/e92WCffZ

Thanks!

**Comment by K-4U** [comment]
Most likely fixed in later version. Sorry for my late reply and thank you for reporting! :)
