### ISSUE TITLE
Hydraulicrash - net.minecraftforge.fml.common.LoaderException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by BBoldt** [K-4U/Hydraulicraft#173]
https://gist.github.com/ef6bbeb618da22d75b1d

**Comment by K-4U** [comment]
Not quite sure what's causing this error. Can you try a newer version and see if the problem persists?

**Comment by Dmitchell94** [comment]
Hi I am using the latest versions of your mod and k4lib as well as 1722 forge. I get the same issue.

Look at line 73 of the crash report and you will see:

```
Caused by: java.lang.RuntimeException: That channel is already registered
	at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:146)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.<init>(SimpleNetworkWrapper.java:113)
	at net.minecraftforge.fml.common.network.NetworkRegistry.newSimpleChannel(NetworkRegistry.java:167)
	at k4unl.minecraft.k4lib.network.NetworkHandler.<clinit>(NetworkHandler.java:36)
```

This seems to be the root of the problem. Looks like something in your network wrapper is off. Random Things had the same type of error and may be able to assist you in fixing the problem:
https://github.com/lumien231/Random-Things/issues/22

**Comment by Tander** [comment]
http://pastebin.com/XXgkJKPv same error.
BTW, it doesn't crash when only Hydraulicraft, multiparts and k4lib presented in pack. So it kind of incompatibility with other mods, i presume.

**Comment by Dmitchell94** [comment]
it seems to be a networking issue where another mod registers the channel before this mod. the fix is to simply change the code to look for the next available channel rather then hard code a channel.

**Comment by K-4U** [comment]
Well, the issue is that i register the channel on "Hydcraft".. There should be no other mod using that channel.
Could you guys give me a modlist of the other mods?

**Comment by BBoldt** [comment]
![](http://i.imgur.com/4opTbyI.png)

**Comment by BBoldt** [comment]
It has to be something that is in both @Dmitchell94 & my packs, but not in FTB Unstable.

**Comment by Dmitchell94** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1408174/12697881/a1d3fd8c-c75b-11e5-9701-f065abd4e017.png)

**Comment by Tander** [comment]
You have full mod list in the crashlog, isn't it? Anyway, here is my modlist: 
![explorer_2016-01-30_23-46-38](https://cloud.githubusercontent.com/assets/1059805/12698358/c5e1619c-c7ab-11e5-92e7-2701d263b58d.png)

**Comment by CallMeFoxie** [comment]
I think I know where the issue is coming from - it might happen when you have >=2 mods using K4lib installed. Will debug tomorrow and hopefully fix.

**Comment by CallMeFoxie** [comment]
Or possibly another mod with the same bug as is in K4Lib :)

**Comment by CallMeFoxie** [comment]
Can you, please, try these updated versions of K4Lib and Hydraulicraft and tell us if it fixed it?
http://jenkins.k-4u.nl/job/K4Lib-1.8.9/lastSuccessfulBuild/artifact/build/libs/k4lib-1.8.9-1.0.9-universal.jar
http://jenkins.k-4u.nl/view/1.8.9/job/Hydraulicraft-1.8.9/lastSuccessfulBuild/artifact/build/libs/HydCraft-1.8.9-3.1.38-universal.jar

note that any other mod using K4Lib will not work with this, they need to be updated

**Comment by Tander** [comment]
Nope, it's another crash
[crash-2016-01-31_13.33.16-client.txt](https://github.com/K-4U/Hydraulicraft/files/111218/crash-2016-01-31_13.33.16-client.txt)

**Comment by CallMeFoxie** [comment]
That is another crash, we will look into it (for some reason the oredictionary has a NULL item registered or something along those lines). But it has fixed the original problem with network.

Now I can say that another mod had the same issue - it was registering a network channel with an empty name. Sadly there is no easy way to find which one it is, unless Forge adds the check on its own.

**Comment by CallMeFoxie** [comment]
I did a cros-section to list common mods between this report and yesterday's report and it works fine on my end. Can you, please, send us your configs or tell us what you have changed/added/removed/..? Same for the tweaker.

**Comment by CallMeFoxie** [comment]
Alright, can you, please, try this K4Lib version?
http://jenkins.k-4u.nl/job/K4Lib-1.8.9/10/artifact/build/libs/k4lib-1.8.9-1.0.10-universal.jar
I've added checks for NULLs in OreDictionary.

**Comment by CallMeFoxie** [comment]
Alright, spent far too much time on this, this is NOT our fault.

This is a bug in the Foundry mod as it adds a smelting recipe with a NULL input item.

[14:44:43] [Client thread/INFO] [FML/HydCraft]: Smelting: !! NULL => 1xitem.ingot@0 @ exter.foundry.creativetab.FoundryTabMaterials@14a8b97c

Cheers.
