### ISSUE TITLE
Hydralicraft seems to be looking for the Thermal Expansion API

### ISSUE THREAD

**Issue by Thoddius** [K-4U/Hydraulicraft#174]
HydraulicDynamo seems to be causing a problem because I don't have Thermal Expansion installed. I don't really want to add the TE API for no reason. Here is the crash report.

[crash-2016-01-21_09.52.49-client.txt](https://github.com/K-4U/Hydraulicraft/files/99603/crash-2016-01-21_09.52.49-client.txt)

**Comment by K-4U** [comment]
There's an option to disable RF in the config. use that for now.

**Comment by Thoddius** [comment]
Thanks for the quick response. I went ahead and added CofHCore anyway to make sure I don't have trouble with any other mods that can use RF.
