### ISSUE TITLE
Server will disconnect all players 1.8.9 

### ISSUE THREAD

**Issue by cauliflower69** [K-4U/Hydraulicraft#175]
http://pastebin.com/tBPqb7ei

**Comment by K-4U** [comment]
What were you doing when this happened?

**Comment by K-4U** [comment]
Okay, found and fixed. New version is going on curse as we speak. However, you may want to temporarily disable "waterPressureKills" in the hydcraft config (only needed on the server). 
That should hold you over till tfox updates the pack.

**Comment by cauliflower69** [comment]
Thanks for the quick fix
