### ISSUE TITLE
ore:Lonezium registered twice

### ISSUE THREAD

**Issue by cauliflower69** [K-4U/Hydraulicraft#176]
http://imgur.com/FYrvQip

Fatally missing blocks and items on trying to login to server then after trying again the above screen 

Using HydCraft-1.8.9-3.1.28-universal.jar

**Comment by K-4U** [comment]
Is this problem still persisting in later versions?

**Comment by cauliflower69** [comment]
To be honest I have not tried. I updated to the latest release via FTB Unstable 3.0.16 and that is when the issue started.

I will update the server later with the latest Hydraulicraft and let you know how it goes.

Did you find out what caused the issue ?

**Comment by K-4U** [comment]
I haven't found out what caused it, just that in this state i push out builds so often, sometimes the problem might be already fixed.

It's also a weird problem, because you're the first one to ever report it, and i haven't changed anything in the code related to ores.

**Comment by zerogott** [comment]
Hes not the only one
but it seems like its a server only problem
singleplayer works fine

**Comment by cauliflower69** [comment]
Yeah very peculiar. I always seem to be "that guy" that finds these odd issues. I will report back later

**Comment by bushbaby1234** [comment]
I was getting this too after the 3.0.16 update. I can try to force it later and get you some info/logs if you want

**Comment by zerogott** [comment]
that was the console error in the FTB launcher console

[19:44:51] [Netty Client IO #4/ERROR] [FML]: Failed to connect to server: there are 1 missing blocks and items
[19:44:51] [Netty Client IO #4/INFO] [FML]: Found a missing id from the world charsettweaks:graphite
[19:44:51] [Netty Client IO #4/INFO] [BuildCraft]: Remap charsettweaks:graphite not used
[19:44:51] [Netty Client IO #4/ERROR] [FML]: Failed to connect to server: there are 1 missing blocks and items

**Comment by bushbaby1234** [comment]
Mine was on a server install too

**Comment by K-4U** [comment]
Interesting. Thanks all for the feedback. I'll be looking into it!

**Comment by zerogott** [comment]
any updates yet?

**Comment by cauliflower69** [comment]
@zerogott Best to wait until they reply with feedback

**Comment by CallMeFoxie** [comment]
I see you are using FTB Unstable pack, it is not happening just in the base game with HC+K4Lib+JEI+Waila+IGW. Will poke it a bit more then.

**Comment by cauliflower69** [comment]
Thanks

**Comment by cauliflower69** [comment]
Same issue with FTB Unstable 3.0.18 (This world is about one month old)

**Comment by K-4U** [comment]
Can you send me your world files?

**Comment by cauliflower69** [comment]
Very strange. Even after removing k4lib and Hyraulicraft from server and client. 

Fatally missing blocks and items so I don't believe you are responsible?

**Comment by LabGoblin** [comment]
https://www.dropbox.com/s/i31sef4b5w1lcrw/world.7z?dl=0
here is my world that i just got the issue in, i can also give you the entire server instance if you need

**Comment by K-4U** [comment]
Any configs changed?
I'm actually almost fairly certain now that it has nothing to do with Hydraulicraft though.

**Comment by cauliflower69** [comment]
If you disable charset it launches fine and you can connect fine so you are correct. Just found the issue!

**Comment by K-4U** [comment]
@asiekierka
