### ISSUE TITLE
Is there a way to retrogen your ores?

### ISSUE THREAD

**Issue by bushbaby1234** [K-4U/Hydraulicraft#178]
Is there a way to retrogen your ores?

**Comment by K-4U** [comment]
As of yet: No. You'll have to use a third party mod to retrogen the ores.

**Comment by bushbaby1234** [comment]
Would your mod be compatible with CPW's Simple retrogen? 
I think I need the mods IWorldGenerator id thing?

https://github.com/cpw/simpleretrogen

Thanks in advance

**Comment by LabGoblin** [comment]
for posterity's sake i got this to work with this IWorldGenerator 
k4unl.minecraft.Hydraulicraft.world.HCWorldGenerator
