### ISSUE TITLE
Startup Crash - NoClassDefFoundError

### ISSUE THREAD

**Issue by TheXWolf** [K-4U/Hydraulicraft#179]
On Startup I got this error:
http://pastebin.com/K9WVsF6e
Thought it might be k4lib related as well, went back 4 versions same issue. Also went back as well tried 3.1.32 just for the point of being thorough; no dice as well.

**Comment by Dmitchell94** [comment]
what versions are you using? Forge, k4lib and Hydraulicraft

**Comment by K-4U** [comment]
Did you install MC Multipart?

**Comment by TheXWolf** [comment]
I cannot find a direct download for multipart for 1.8.9 and running CB crashes me; so no I don't have FMP for 1.8.9 running as none of my other mods needed it, but since I can do what it normally does without a file, I assumed it was included in the forge release. Forge 1726 - Hydra 3.1.25 through 3.1.34 using k4lib 189 1.0.8

**Comment by K-4U** [comment]
No. You need mc multipart, it's a new mod by amadornes. If you download on curse you should see the fact that it's required. Go check on the details of the file.

**Comment by TheXWolf** [comment]
Gotcha, never looked at the page the files was only used the quick download button. When I had multiblock support the way the older forge one had I assumed it was in there, wasn't aware it was something new/different. _(Maybe consider putting the requirement on the main page)_ Thanks @K-4U all is well and good now.
