### ISSUE TITLE
jei crash with one of your recipe 

### ISSUE THREAD

**Issue by damew** [K-4U/Hydraulicraft#181]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  thaumicinfusion (ThaumicInfusion-4.77.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.1BETA.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  CorePlugin (Fluxed Redstone-1.1.0.16.jar)
  BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-29.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 1/31/16 11:15 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at k4unl.minecraft.Hydraulicraft.thirdParty.jei.JEICategoryAbstract.setRecipe(JEICategoryAbstract.java:84)
	at mezz.jei.gui.RecipeLayout.<init>(RecipeLayout.java:51)
	at mezz.jei.gui.RecipeGuiLogic.getRecipeWidgets(RecipeGuiLogic.java:218)
	at mezz.jei.gui.RecipesGui.updateLayout(RecipesGui.java:349)
	at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:322)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:319)
	at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:242)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:218)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at k4unl.minecraft.Hydraulicraft.thirdParty.jei.JEICategoryAbstract.setRecipe(JEICategoryAbstract.java:84)
	at mezz.jei.gui.RecipeLayout.<init>(RecipeLayout.java:51)
	at mezz.jei.gui.RecipeGuiLogic.getRecipeWidgets(RecipeGuiLogic.java:218)
	at mezz.jei.gui.RecipesGui.updateLayout(RecipesGui.java:349)
	at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:322)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:319)
	at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:242)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:218)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: mezz.jei.gui.RecipesGui

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP[..., l='MpServer', x=30.38, y=66.00, z=71.03]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 12.00,64.00,211.00 - World: (12,64,211), Chunk: (at 12,4,3 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 522474 game time, 370737 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntitySkeleton['Skeleton'/116613, l='MpServer', x=94.50, y=41.00, z=78.50], EntityBackpack['entity.ironbackpacks.EntityBackpack.name'/2844, l='MpServer', x=30.38, y=66.00, z=71.03], EntityPlayerSP[..., l='MpServer', x=30.38, y=66.00, z=71.03], EntityPig['Pig'/2846, l='MpServer', x=41.22, y=64.00, z=7.91], EntitySkeleton['Skeleton'/111390, l='MpServer', x=-7.50, y=30.00, z=130.50], EntityBat['Bat'/117662, l='MpServer', x=-21.50, y=21.97, z=131.58], EntityPig['Pig'/2848, l='MpServer', x=74.75, y=74.00, z=14.47], EntityAuraNode['Aura Node'/2849, l='MpServer', x=-8.50, y=73.50, z=-10.50], EntityPig['Pig'/2852, l='MpServer', x=69.22, y=70.00, z=-0.81], EntityAuraNode['Aura Node'/2737, l='MpServer', x=-47.50, y=71.50, z=159.50], EntityAuraNode['Aura Node'/2738, l='MpServer', x=-19.50, y=66.50, z=70.50], EntityRabbit['Rabbit'/2739, l='MpServer', x=-8.13, y=75.00, z=25.47], EntityVillager['Villager'/2740, l='MpServer', x=-1.50, y=69.00, z=94.72], EntityVillager['Villager'/2741, l='MpServer', x=-5.09, y=69.00, z=100.53], EntityVillager['Villager'/2742, l='MpServer', x=-1.31, y=69.00, z=102.69], EntityVillager['Villager'/2743, l='MpServer', x=-2.31, y=69.00, z=97.53], EntityVillager['Villager'/2744, l='MpServer', x=-4.59, y=69.00, z=98.75], EntitySkeleton['Skeleton'/115769, l='MpServer', x=74.72, y=32.00, z=68.88], EntityVillager['Villager'/2745, l='MpServer', x=-7.31, y=69.00, z=101.69], EntityVillager['Villager'/2746, l='MpServer', x=-7.72, y=69.00, z=102.69], EntityRabbit['Rabbit'/2875, l='MpServer', x=-37.38, y=72.00, z=-1.94], EntityVillager['Villager'/2747, l='MpServer', x=-6.19, y=69.00, z=101.53], EntitySkeleton['Skeleton'/36667, l='MpServer', x=42.84, y=45.00, z=69.69], EntityVillager['Villager'/2748, l='MpServer', x=-5.19, y=69.00, z=101.78], EntityVillager['Villager'/2749, l='MpServer', x=-2.38, y=69.00, z=102.34], EntityVillager['Villager'/2750, l='MpServer', x=-5.72, y=69.00, z=102.69], EntityVillager['Villager'/2751, l='MpServer', x=-1.50, y=68.00, z=108.72], EntityVillager['Villager'/2753, l='MpServer', x=-3.78, y=68.00, z=109.44], EntityAuraNode['Aura Node'/2754, l='MpServer', x=0.50, y=75.50, z=122.50], EntityVillager['Villager'/2755, l='MpServer', x=4.28, y=67.00, z=120.44], EntityRabbit['Rabbit'/2756, l='MpServer', x=16.47, y=65.00, z=91.88], EntityAuraNode['Aura Node'/2757, l='MpServer', x=18.50, y=65.50, z=119.50], EntityRabbit['Rabbit'/2763, l='MpServer', x=51.00, y=65.00, z=140.50], EntityPig['Pig'/2765, l='MpServer', x=57.44, y=62.53, z=48.44], EntityBat['Bat'/43086, l='MpServer', x=46.50, y=47.10, z=66.22], EntityPig['Pig'/2771, l='MpServer', x=80.41, y=69.00, z=16.44], EntityAuraNode['Aura Node'/2773, l='MpServer', x=91.50, y=64.50, z=163.50], EntityChicken['Chicken'/2775, l='MpServer', x=103.59, y=62.56, z=83.47], EntityPig['Pig'/2776, l='MpServer', x=107.97, y=63.00, z=82.94], EntityAuraNode['Aura Node'/2778, l='MpServer', x=109.50, y=70.50, z=98.50], EntityAuraNode['Aura Node'/2779, l='MpServer', x=120.50, y=91.50, z=30.50], EntitySkeleton['Skeleton'/116189, l='MpServer', x=42.50, y=17.00, z=53.50], EntityAuraNode['Aura Node'/31591, l='MpServer', x=-78.50, y=71.50, z=38.50], EntityCreeper['Creeper'/11118, l='MpServer', x=42.59, y=45.00, z=68.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 844730712 bytes (805 MB) / 2659696640 bytes (2536 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1723 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1723.jar) 
	UCHIJAAAA	Forge{11.15.1.1723} [Minecraft Forge] (forge-1.8.9-11.15.1.1723.jar) 
	UCHIJAAAA	bowinfinityfix{rv2} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJAAAA	ActuallyAdditions{1.8.9-r23} [Actually Additions] (ActuallyAdditions-1.8.9-r23.jar) 
	UCHIJAAAA	FurnaceEvolved{1.8.9-0.0.1.3} [Furnace Evolved] (Alt-F4-0.0.1.3.jar) 
	UCHIJAAAA	AnimeCraft{1.5.0} [AnimeCraft] (AnimeCraft Vol 1.5.zip) 
	UCHIJAAAA	AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
	UCHIJAAAA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9 .jar) 
	UCHIJAAAA	bigtrees{0.2} [The BigTrees Mod] (bigtrees-0.2-1.8.9.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-13} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-13.jar) 
	UCHIJAAAA	bookshelfapi{2.2.5} [Bookshelf] (Bookshelf-1.8.9-2.2.5.jar) 
	UCHIJAAAA	cannibalism{1.2.2} [Cannibalism] (Cannibalism-2.2.2-1.7.10.jar) 
	UCHIJAAAA	caterpillar{0.0.0} [Caterpillar] (Caterpillar-0.1.189b73.jar) 
	UCHIJAAAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAAAA	ChestTransporter{2.2.0} [Chest Transporter] (ChestTransporter-2.2.0-MC1.8.9.jar) 
	UCHIJAAAA	mcmultipart{1.0.5} [MCMultiPart] (MCMultiPart-1.0.5-universal.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.6} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.6.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.8.9-v1b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v1b.jar) 
	UCHIJAAAA	ElecCore{1.4.220} [ElecCore] (ElecCore-1.8.9-1.4.220.jar) 
	UCHIJAAAA	CraftingTableIV{1.2.84} [CraftingTableIV] (CraftingTableIV-1.8.9-1.2.84.jar) 
	UCHIJAAAA	CrissCross{1.3.9.1} [Criss Cross] (CrissCross-1.8.9-1.3.9.1.jar) 
	UCHIJAAAA	DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0.jar) 
	UCHIJAAAA	dsurround{2.0.4.1BETA} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.1BETA.jar) 
	UCHIJAAAA	EFlux{1.0Alpha.96} [EFlux] (E-Flux-1.8.9-1.0Alpha.96.jar) 
	UCHIJAAAA	ShetiPhianCore{3.0.3} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.0.3.jar) 
	UCHIJAAAA	EnderTanks{1.2.0} [EnderTanks] (EnderTanks-1.8.9-1.2.0.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.8.9-1.3.3} [Extra Bit Manipulation] (ExtraBitManipulation-1.8.9-1.3.3.jar) 
	UCHIJAAAA	FFS{1.8.9-1.4.4.68} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.4.4.68.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.6.jar) 
	UCHIJAAAA	reborncore{1.4.0.13} [RebornCore] (RebornCore-1.8.9-1.4.0.13-universal.jar) 
	UCHIJAAAA	fluxedredstone{1.1.0.16} [FluxedRedstone] (Fluxed Redstone-1.1.0.16.jar) 
	UCHIJAAAA	fluxedsolars{$GRADLEVERSION} [Fluxed Solars] (fluxedsolars-1.8.jar) 
	UCHIJAAAA	samsfooddetails{1.0.0} [Food Details] (FoodDetails-1.8.9-1.0.0.jar) 
	UCHIJAAAA	GlobalGameRules{1.0} [Global GameRules] (GlobalGameRules-1.8.9-1.0.jar) 
	UCHIJAAAA	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
	UCHIJAAAA	howlingmoon{1.0.1} [Howling Moon] (howlingMoon-1.8.9-1.0.1.jar) 
	UCHIJAAAA	k4lib{1.8.9-1.0.8} [K4Lib] (k4lib-1.8.9-1.0.8-universal.jar) 
	UCHIJAAAA	HydCraft{1.8.9-3.1.34} [Hydraulicraft] (HydCraft-1.8.9-3.1.34-universal.jar) 
	UCHIJAAAA	inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
	UCHIJAAAA	inventorytweaks{1.60-beta-29-c6fa1db} [Inventory Tweaks] (InventoryTweaks-1.60-beta-29.jar) 
	UCHIJAAAA	ironbackpacks{1.8.9-2.0.4} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.4.jar) 
	UCHIJAAAA	IronChest{6.0.123.769} [Iron Chest] (ironchest-1.8.9-6.0.123.769.jar) 
	UCHIJAAAA	JEI{2.24.2.125} [Just Enough Items] (jei_1.8.9-2.24.2.125.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.4} [Thaumcraft] (Thaumcraft-1.8.9-5.1.4.jar) 
	UCHIJAAAA	JEIAddons{0.10.1.39} [Just Enough Items Addons] (JEIAddons_1.8.9-0.10.1.39.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	jeresources{0.3.1} [Just Enough Resources] (JustEnoughResources-1.8.9-0.3.1.jar) 
	UCHIJAAAA	jwin{univ_compat_filler} [Just What I Needed] (JWIN_v0.10.3_1.8.9.jar) 
	UCHIJAAAA	llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
	UCHIJAAAA	m4ththings{@VERSION@} [M4th Things] (m4ththings-1.8.9_0.0.1-alpha.jar) 
	UCHIJAAAA	mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	ModNameTooltip{1.0.0} [Mod Name Tooltip] (modnametooltip_1.8.8-1.0.0.jar) 
	UCHIJAAAA	MysticalCrops{1.1} [Mystical Crops] (Mystical Crops-1.2.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar) 
	UCHIJAAAA	neotech{2.3.0} [NeoTech] (NeoTech-1.8.9-2.3.0.jar) 
	UCHIJAAAA	fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
	UCHIJAAAA	PneumaticCraft{1.13.5-6} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.5-6-universal.jar) 
	UCHIJAAAA	progressiveautomation{1.6.33} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.33.jar) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.3} [ProjectE] (ProjectE-1.8.9-PE1.1.3.jar) 
	UCHIJAAAA	quantumflux{2.0.0-b1} [QuantumFlux] (quantumflux-1.8.9-2.0.0-b1.jar) 
	UCHIJAAAA	RandomThings{3.5.8} [Random Things] (RandomThings-MC1.8.9-3.5.8.jar) 
	UCHIJAAAA	RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
	UCHIJAAAA	xreliquary{1.3-alpha1.82} [Reliquary] (Reliquary-1.3-alpha1.82.jar) 
	UCHIJAAAA	rftools{4.20beta14} [RFTools] (rftools-1.8.9-4.20beta14.jar) 
	UCHIJAAAA	rftoolsdim{4.20beta15} [RFTools Dimensions] (rftoolsdim-1.8.9-4.20beta15.jar) 
	UCHIJAAAA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJAAAA	sem{1.4.3} [Steam Engines Mod] (sem-mc1_8_9-1.4.3.jar) 
	UCHIJAAAA	semmagie{1.4.3} [Steam Engines Mod - Magie Addon] (sem-mc1_8_9-1.4.3.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors] (SimilsaxTranstructors-1.8.8.16.jar) 
	UCHIJAAAA	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UCHIJAAAA	SoulMagic{1.0.0} [SoulType Magic] (SoulMagic-1.8.9-1.0.2pr.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.3.0} [Storage Drawers] (StorageDrawers-1.8.9-2.3.0.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
	UCHIJAAAA	techreborn{0.7.9.45} [TechReborn] (TechReborn-1.8.9-0.7.9.45-universal.jar) 
	UCHIJAAAA	thaumicbases{1.4.189.23} [Thaumic Bases] (ThaumicBases-2.1.189.23.jar) 
	UCHIJAAAA	thaumicinfusion{4.77} [Thaumic Infusion] (ThaumicInfusion-4.77.jar) 
	UCHIJAAAA	thaumicstorage{0.2.1.1} [Thaumic Storage] (ThaumicStorage-0.2.1.1.jar) 
	UCHIJAAAA	thelittlethings{1.2.2-Forge1.8.9} [The Little Things] (The Little Things-v.1.2.2-mc1.8.9.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.6.jar) 
	UCHIJAAAA	wawla{1.4.1} [What Are We Looking At] (Wawla-1.4.1-1.8+.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
thaumicinfusion (ThaumicInfusion-4.77.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  lumien.randomthings.asm.ClassTransformer
CorePlugin (Fluxed Redstone-1.1.0.16.jar)
  
BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  com.github.parker8283.bif.Transformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
FMLPlugin (InventoryTweaks-1.60-beta-29.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore''Thaumic Infusion'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1723
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by CallMeFoxie** [comment]
"jei crash with one of your recipe" <-- which one? Or which machine?
