### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by whyo2** [K-4U/Hydraulicraft#182]
Getting crash when starting mod latest version. All requirements up to date
https://pastee.org/yfrcv

**Comment by CallMeFoxie** [comment]
k4lib{1.8.9-1.0.8} K4Lib (k4lib-1.8.9-1.0.8-universal.jar) 

Your requirements are not up to date, you need to use 1.0.9 or newer.

Ashley

**Comment by whyo2** [comment]
sorry i guess thats just my curse voice messing up, doesnt have update sign next to it in the mod list

**Comment by K-4U** [comment]
Please read changelogs. It's mentioned in there!

**Comment by CallMeFoxie** [comment]
Curse has possibly not propagated the changes everywhere yet (no idea), no worries ^^
