### ISSUE TITLE
HydCraft.cfg resetting

### ISSUE THREAD

**Issue by rckymtnrfc** [K-4U/Hydraulicraft#184]
I've made changes in the HydCraft.cfg, to disable bacon (added from another mod) and to turn off copper ore.

When I restart  Minecraft (or the server) the cfg file resets to default settings.

**Comment by rckymtnrfc** [comment]
Hum, maybe you are writing to the cfg file on the 2nd loading of the mod?  I deleted the config file, let it regen.  Closed MC, made some edits to the config, restarted MC and the config appears to reset.  I then made the changes again and they are staying but I'm now getting this crash on the client.

http://pastebin.com/NtTpG2DN

**Comment by K-4U** [comment]
Hmm, i can fix the crash with the bacon, just not the config resetting. I'll have to do a bit more research on that.

**Comment by rckymtnrfc** [comment]
The config reset seemed to stop after I loaded up the 3rd time. 

So, if I enable bacon I can work around this crash for now?  Because honestly, you can't have too much bacon. =)

**Comment by K-4U** [comment]
Yeah, if you enable bacon you can work around the crash. I've already fixed the crash locally, just doing some more work ;)
