### ISSUE TITLE
Miner's Helmet light "blocks" cannot be removed, player cannot pass through.

### ISSUE THREAD

**Issue by TheDarkPreacher** [K-4U/Hydraulicraft#185]
So i was playing FTB Unstable, which has Hydraulicraft v. 1.8.9-3.1.41-41, and I decided to make the miner's helmet. I placed it on my character, hit the hotkey to turn it on (L in this case) and was immediately shoved back and to the side because it was placing invisible, indestructible blocks that create light. I can't destroy them, and I can't see nor pass through them.

**Comment by K-4U** [comment]
Fixed in build 48 ;)
