### ISSUE TITLE
Friction Incinerator related crash 

### ISSUE THREAD

**Issue by TheDarkPreacher** [K-4U/Hydraulicraft#186]
Built the Friction incinerator, hooked it up to a low pressure system, opened GUI, inserted crushed copper from hydraulicraft crusher, immediately crashed. reloaded world, everything was fine, tried opening Friction incinerator again, crash.

http://pastebin.com/RAhfdvNu

**Comment by CallMeFoxie** [comment]
Update your K4Lib to 1.0.12, please
