### ISSUE TITLE
client crash when pressing "R" key over copper ore recipe

### ISSUE THREAD

**Issue by tntblockman** [K-4U/Hydraulicraft#187]
Minecraft: 1.8.9
FTB Unstable pack: 3.0.20
Hydraulicraft: 3.1.50

Client crash when pressing "R" key over HC copper ore recipe.  

Tested on lead ore without crashing.
Tested NeoTech copper ore which crashed client.
Tested (only other copper ore in pack) NeoTech copper ore with Hydraulicraft disabled without          crashing.

crash report: http://pastebin.com/XwEnEDH4

**Comment by tntblockman** [comment]
Also tested with Unstable pack: 3.0.22, Hydraulicraft: 3.1.57 http://pastebin.com/suKG9LjJ

**Comment by K-4U** [comment]
Quite possibly not my crash, appears to be fixed in later versions of FTB Unstable.
Closing for now, can reopen if it happens again.

**Comment by K-4U** [comment]
Fixed in https://github.com/EXTER7/OreDictionaryConverter/issues/9
Poke Q to  update this mod
