### ISSUE TITLE
Washer/Crusher no longer process after chunk(s) unloads/reloads

### ISSUE THREAD

**Issue by tntblockman** [K-4U/Hydraulicraft#192]
Minecraft: 1.8.9
Hydraulicraft: all 1.8.9 versions tested upto 3.1.65
FTB Unstable pack: upto 3.0.27

Hi,
During Washer/Crusher processing cycle of resources(ores), the unloading and reloading of chunk(s) they are placed in. Washer and Crusher processing cycle becomes in a state of "stuck", and will no longer process any current or further resources.

You can still access their GUIs.
You can still place, replace the resources within the GUI.
Water/pressure levels still display.
Quick fix: is to break and replace the machines.

Replicate issue by creating a simple Washer and Crusher setup.  Allow them to start processing resources.  Then move far enough away to unload the chunks they are placed within. Come back to the area, open their GUI, and observe they no longer process the resources.  Taking out/replacing the resources has no effect on the issue.

Note#1: This issue seems to only occur when they are in processing cycle. 
Note#2: Could also effect other machines but not tested.

**Comment by K-4U** [comment]
Related: http://pastebin.com/McuYPdcB
