### ISSUE TITLE
pipes are easy to get stuck on when standing ontop

### ISSUE THREAD

**Issue by tntblockman** [K-4U/Hydraulicraft#194]
Minecraft: 1.8.9
Hydraulicraft: all 1.8.9 versions tested upto 3.1.65
FTB Unstable pack: upto 3.0.27

When standing ontop of pressure (any version) pipes it's easy to get stuck on them.  Fix is to break the pipe your stuck on.

**Comment by K-4U** [comment]
@amadornes I'm probably missing a method or something. Could you have a look at what i'm doing wrong?
