### ISSUE TITLE
invisible ore blocks

### ISSUE THREAD

**Issue by LabGoblin** [K-4U/Hydraulicraft#197]
on my server i keep finding invisible blocks that you cant break or place anything in and if i blow them up i often get some hydraulicraft ore.

**Comment by K-4U** [comment]
I have no idea how to even begin with this..

Let's try some basic questions: What version of forge, Hydraulicraft and K4Lib are you running.
Also, what exact ores are you getting?

**Comment by LabGoblin** [comment]
my apologies. i never know what info is needed.
forge:1724
Hc:3.1.64
K4Lib:1.0.16

I've gotten lonezium, copper, and lead. the odd part is that i've seem copper not invisible. it seems this may have happened at an older version. as i cant seem to replicate it...

**Comment by K-4U** [comment]
Well, if it isn't happening in the latest version, we can close it ;)

**Comment by LabGoblin** [comment]
i was finally able to replicate it. i think its something weird on my server. everything that worldgens from your mod is invisible it seems. i just made an RFTools dimension for everyone to mine in on my server and found more invisible ores. lonezium and copper confirmed so far

what all info would you like/need to advance this

Forge: 1746
Hc:3.1.65
K4Lib:1.0.16

**Comment by K-4U** [comment]
Wait, everything that generates from my mod is invisible. Are they visible when you replace them? Are any other blocks invisible?

**Comment by LabGoblin** [comment]
apparently everything is invisible...

**Comment by K-4U** [comment]
I think you have more problems than just my ores.. I also really think it's on your side, as i would've noticed blocks being invisible.

**Comment by LabGoblin** [comment]
everything from your mod is invisible\* and i think i am special when it comes to this.... because ive never even heard of something like this happening. it may have something to do with the new forge thing where it keeps block info after you remove a mod, because i had a few conflicts earlier on where i had to remove hc and i think its the only mod in the pack that has been removed then later readded....

**Comment by K-4U** [comment]
Oh! I've had that in the past too. With buildcraft, screwed an entire world over.. This may be something to take up with them

**Comment by LabGoblin** [comment]
can do. now to find their issue tracker. thanks for your time. and best of luck with the hard drive
