### ISSUE TITLE
Filter stopped working in HydCraft-1.8.9-3.1.64

### ISSUE THREAD

**Issue by XewTurquish** [K-4U/Hydraulicraft#198]
I've started a world with only the following mods: Bookshelf-1.8.9-2.3.0.jar, jei_1.8.9-2.25.11.150.jar, k4lib-1.8.9-1.0.16-universal.jar, MCMultiPart-1.0.6-universal.jar, NeoTch-1.8.9-2.3.5.jar. I've tried HydCraft-1.8.9-3.1.64, HydCraft-1.8.9-3.1.65, and HydCraft-1.8.9-3.1.57. 

Only HydCraft 3.1.57 will the filter convert Oil to Hydraulic Oil. The block used as the filter disappears but the machine does not convert.

**Comment by K-4U** [comment]
I already fixed this in an upcoming version. Could you try with the version on my jenkins? http://jenkins.k-4u.nl/job/Hydraulicraft-1.8.9/70/ (please use just for testing this issue, don't use it in your world)

**Comment by XewTurquish** [comment]
My main world has alot more mods in it. Created a new world with just the mods to test the issue. Version 70 work after I replaced the Filter.
