### ISSUE TITLE
Instant death if player forget to fill up his diving suit

### ISSUE THREAD

**Issue by tntblockman** [K-4U/Hydraulicraft#200]
Minecraft: 1.8.9
Hydraulicraft: 3.1.65
FTB Unstable pack: 3.0.28

Issue related to instant death if player forget to fill up his diving suit.  Perhaps this needs to be scaled back to something similar to damage you take when you run out of air whilst drowning in water?

**Comment by K-4U** [comment]
Instant death was mostly intended, but i'll nerf the damage a bit :)

**Comment by K-4U** [comment]
Also Wooh! Issue #200! :D
