### ISSUE TITLE
WorldGenOil crash with SpongeForge

### ISSUE THREAD

**Issue by ajthemacboy** [K-4U/Hydraulicraft#202]
Crash report: https://gist.github.com/ajthemacboy/65145602dc6175478da4

This crash only occurs with SpongeForge installed. This occurs on Forge 1732 with the latest version of SpongeForge installed.

**Comment by K-4U** [comment]
Duplicate of #188

**Comment by ajthemacboy** [comment]
Are you certain this is a duplicate?

This crash ONLY occurs with the SpongeForge mod installed, and the crash directly mentions Sponge.
