### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by DrPlantabyte** [K-4U/Hydraulicraft#204]
Hello Hydraulicraft authors.

I'm sorry for being blunt, but I'm tired of receiving complaints about problems with lead and copper ingots from users of my Base Metals mod. The problem is that your code is being overly clever with its attempt to substitute its own lead and copper with that provided by other mods, resulting in many bugs that I bet are annoying you as much as they are annoying me. 

My request is that you remove all of the detection code and simply add your lead and copper to the game registry regardless to what other mods are installed. So long as your recipes use the Ore Dictionary, it doesn't matter whether users craft with Base Metals, Hydraulicraft, or other mod ingots and users can set the ore spawning to 0 in either of our mods to decide for themselves which mod's ingots they want to use.

Please don't interpret the above as meaning that I dislike your mods or yourselves. Despite the above, I admire Hydraulicraft both for its cool concept (hydraulics) and clean code.

Best wishes,
-DrCyano

**Comment by K-4U** [comment]
Hello DrCyano,

You're not blunt, i understand the annoyance of people reporting issues with your mod that you didn't cause yourself. 

I just realized that although all the ore code is out, the ingots still do the same. I've just removed that code, and it won't be in the next update.

Thanks for making your request!

With kind regards,
~K4Unl
