### ISSUE TITLE
Instacrash

### ISSUE THREAD

**Issue by Darktotaled** [K-4U/Hydraulicraft#205]
got a instacrash where hydraulicraft errored in the pre-initializing stage
k4lib version 1.0.16
Hydraulicraft version 3.1.65

here is a print of the crash log

http://prntscr.com/a4aenc

if you need anything else just ask

**Comment by K-4U** [comment]
Please install MCMultipart. There'll be a message for that in the next build

**Comment by Darktotaled** [comment]
Thanks m8. Realized that this was the problem and went searching for it but only found 1.7.10 versions so i went to bed as it was 3 am. It's working now. Thanks again
