### ISSUE TITLE
loading crash

### ISSUE THREAD

**Issue by firewolf31** [K-4U/Hydraulicraft#207]
i am loading a 1.8.9 modpack with 77 mods install and it loads fine but when i load a modpack with only jei and hydraulicraft and the k4lib/mcmultipart pre reqs. it crashes on load i dont understand even just the 3 mods hydraulicraft/mcmultiparts/k4lib crashes on load.

http://pastebin.com/A9apCmcX pastebin of crash log

p.s Using Curse Voice

**Comment by K-4U** [comment]
Disable the RF in the config, or add a mod with RF in it

**Comment by firewolf31** [comment]
yes thats would be it i just figured it out  thanks :D

**Comment by firewolf31** [comment]
off topic here but resone for doing loading just hydraulicraft arent there any pipes to connect the machines with i do not see them in jei.

**Comment by K-4U** [comment]
They exist, just have no item model yet.. Jei has a config about that

**Comment by firewolf31** [comment]
thanks again
