### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by Darktotaled** [K-4U/Hydraulicraft#208]
first time trying your mod. I don't know how to use it. Tried what i read on the in-game wiki mod and got this   http://prntscr.com/a5kgks

should it pull water? it isn't '-'
last version on curse, both lib and hydraulicraft.

**Comment by K-4U** [comment]
The screw needs power(pressure) to function. It won't output into the network, but into a nearby fluid handler (so any thing you can normally pump fluids into, like a tank, or the reservoir)

If you need any help on how to use the mod, that you cannot find in the in-game wiki mod, please stop by the IRC channel: #hydraulicraft on irc.esper.net

**Comment by Darktotaled** [comment]
what i've learned from the mod was through direwolf20 spotlight, so i still waiting for the vat and the pipes as is appears in the in-game wiki with no recipes and no image, just teh name
