### ISSUE TITLE
Hydraulicraft Oil not being recognized by Buildcraft Pump

### ISSUE THREAD

**Issue by drewbit** [K-4U/Hydraulicraft#210]
Pump is set up correctly. 4 redstone engines, oil has a place to be output to. Engines are pumping. The little spout simply doesn't come out of the pump. Unsure if it's on Hydraulicraft's side or on Buildcraft's. Also unsure if this is intended behavior, not very familiar with this mod so apologies.

Using Buildcraft-7.2.0-pre11 and HydCraft-1.8.9-3.1.64-universal. Not sure what other information to give.

**Comment by buggo** [comment]
I have the same problem.

If you pick the Hydraulicraft oil in a bucket and then place it back under the pump it is converted to BC oil. The pump then pumps only that block that you placed. So there seem to be some kind of missmatch.

I'm running FTB Unstable 3.0.42

**Comment by K-4U** [comment]
Either already fixed, or not reproducable. Let me know if it's fixed with the new version(upcoming)

**Comment by jpiermarini** [comment]
@K-4U  May want to re open this, we are running the latest version of Buildcraft and Hydraulicraft and we aren't able to use the buildcraft pump on Hydraulicraft oil

**Comment by mwoodward** [comment]
@K-4U Just want to piggyback on what @jpiermarini said. We are using the latest 1.8.9 versions of Buildcraft and Hydraulicraft, and are unable to pump oil. The suction tube won't even extend when the pump in place above the oil, so it does not look like the pump even recognizes it as a liquid.
