### ISSUE TITLE
Suggestion: New rubber tree shape

### ISSUE THREAD

**Issue by BBoldt** [K-4U/Hydraulicraft#211]
![](http://i.imgur.com/YbmcZLM.png)

Also you should make the leaves transparent.

Also you should make them only spawn in swamps and jungles.

:P

**Comment by K-4U** [comment]
Is that leaves all the way to the top? Or is there a log in the middle? Maybe a cross section would be handy :p

I've never liked the current rubber tree design, so this one is already better xD

**Comment by BBoldt** [comment]
Logs all the way up, except for the top block, which is leaves.

Based the design on this:

http://previews.123rf.com/images/likephotoman/likephotoman1205/likephotoman120500132/13497447-Para-rubber-tree-garden-in-south-of-Thailand-Stock-Photo.jpg
