### ISSUE TITLE
Missing Recipes in JEI

### ISSUE THREAD

**Issue by Kilandor** [K-4U/Hydraulicraft#212]
Using HydCraft-1.8.9-3.1.65-universal
jei_1.8.9-2.26.0.154
JEIAddons_1.8.9-0.11.2.56
k4lib-1.8.9-1.0.16-universal
MCMultiPart-1.0.7-universal

In JEI I am missing recipes for Pipes, and the Diving Suit.

I think the rest all show up, i'm new to the mod. Also it seems to be missing a lot of the texures for the inventory, such as pipes, or diving suit.

Using a custom modpack, however you can see the Same problems in FTB Unstable 1.8

**Comment by K-4U** [comment]
Jei has an option to hide items with a missing item texture. This is still the case for some of my items. Disable that option, and you should be able to find them in JEI
