### ISSUE TITLE
Copper Ingot missing texture

### ISSUE THREAD

**Issue by shortybsd** [K-4U/Hydraulicraft#216]
When running the latest release of Hydraulicraft HydCraft-1.8.9-3.1.65-universal it messes up BaseMetals copper and lead ingots texture. This was quoted for the reasoning from BaseMetal's dev 

"Hydraulicraft unregisters its ingots when it detects ingots from other mods, but the unregistration is incomplete."

Is there a fix for this?

**Comment by K-4U** [comment]
What version of k4lib are you running?

**Comment by shortybsd** [comment]
k4lib-1.8.9-1.0.14-universal, will update to k4lib-1.8.9-1.0.16-universal now though.

Running MCMultipart version MCMultiPart-1.0.7-universal

**Comment by K-4U** [comment]
Ah wait. I moved this code back to Hydraulicraft. I've already fixed the issue with unregistering, I just never got a chance to push it to curse yet.

**Comment by shortybsd** [comment]
Sweet, I'll be looking for a newer build :), can't wait. Thanks brother!

**Comment by shortybsd** [comment]
Any ETA on the push to curse for newer build?
