### ISSUE TITLE
washer not forming

### ISSUE THREAD

**Issue by mbos14** [K-4U/Hydraulicraft#219]
in the latest version thats in the ftb unstable pack. the washer is not forming a multiblock structure

**Comment by K-4U** [comment]
Could you try rotating it 90 degrees? It's possible that bug hasn't been fixed yet in the version in FTB Unstable...

**Comment by mbos14** [comment]
we made it facing north wich didnt work. now we rotated it so it faced south so now i works. it also needs to be kept chunk loaded else the structure isnt a multiblock anymore.

**Comment by K-4U** [comment]
Yeah, I believe this is all fixed in a later version, which I hope to release somewhere this week. But life is catching up..
