### ISSUE TITLE
Smelting Bucket of Rubber does not return bucket

### ISSUE THREAD

**Issue by TheDestroyer19** [K-4U/Hydraulicraft#225]
### What were you doing when the issue happened?

Starting out a new game, after acquiring a bucket of rubber from the rubber tree. Then I put the bucket of rubber into the furnace along with some coal as fuel. After it finished smelting the bar of rubber appeared but the bucket was consumed.
### What did you expect to happen?

I expected smelting to return an empty bucket in addition to the bar of rubber.
### What happened instead

After smelting only a bar of rubber was available in the furnace.
### Crashlog on pastebin/gist

This issue did not cause a crash. Below is provided the fml-client-latest.log file which should contain any relevant info.
https://gist.github.com/TheDestroyer19/4670c5eba42efd41d845e44d430cc849
### Forge and Minecraft version

Minecraft 1.8.9
Forge 1.8.9-11.15.1.1808
### Hydraulicraft version and build number

HydCraft-1.8.9-3.1.82-universal
### K4Lib version

k4lib-1.8.9-1.0.18-universal

**Comment by K-4U** [comment]
Not persé a bug, more of a feature, it IS intended behaviour.
If this is really a big complaint, i'll see about another method of smelting the rubber.

**Comment by bookerthegeek** [comment]
You can return the bucket along with the bar...

**Comment by K-4U** [comment]
Not possible unless i rescript the furnace. The furnace only has one output slot.

**Comment by bookerthegeek** [comment]
Derp
