### ISSUE TITLE
harvester agricraft trolley - missing recipe!

### ISSUE THREAD

**Issue by Vine999** [K-4U/Hydraulicraft#228]
### What were you doing when the issue happened?

Basic mod testing in creative - to make sure my modding won't cause any errors or conflicts before I launch into a fresh SP world. Hydraulicraft was my current focus, seeing if I could get the harvester to work. 
### What did you expect to happen?

constructed the harvester, and was expecting to find the agricraft trolley to have a recipe, as displayed by NEI.
### What happened instead

The agricraft trolley does not have a visible recipe, instead showing the recipe for the Pneumaticraft plastic plants trolley. Also, neither have a simplified name instead of the "entity.name"-type naming, but that's an aside.
### Crashlog on pastebin/gist

simply open NEI, and attempt to find the recipe for the agricraft trolley, whatever your keybinding is set to. As reported, the wrong recipe and output is displayed.
### Forge and Minecraft version

forge 10.13.4.1614 for minecraft 1.7.10
### Hydraulicraft version and build number

HydCraft-1.7.10-2.1.253-universal
### K4Lib version

k4lib-1.7.10-0.1.57-universal

Also, NEI: NotEnoughItems-1.7.10-1.0.4.107-universal

**Comment by K-4U** [comment]
Surprisingly this is an issue with agricraft.

**Comment by Vine999** [comment]
really? huh. I'm using agrigraft 1.5.0 for the same MC instance. I'm assuming the build that the compatability works in is a different one?

edit: nvm, I've poked around the agricraft page, that is the one the compat's added in. guess I'll poke agricraft's author about it. Thanks for taking the time with this! And thank you for releasing the mod!
